site_name: HoverStop Documentation
site_url: https://hover-stop.github.io/docs
repo_url: https://github.com/hover-stop/docs

theme:
  name: material
  palette:
    primary: blue
    accent: orange
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - meta
  - attr_list

extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js

use_directory_urls: true

docs_dir: ./docs
site_dir: ./site

nav:
  - Home: index.md
  - Build Guides:
      - Overview: build-guides/index.md
      - Wire Lacing Guide: build-guides/wire-lacing-guide.md
      - Wire-to-Component Soldering: build-guides/wire-to-component-soldering.md
      - Turret Soldering: build-guides/turret-soldering.md
  - Design Guides:
      - Electrical Design Guide: design-guides/electrical-design-guide.md
      - Hardware Design Guide: design-guides/hardware-design-guide.md
  - Technical Data: technical-data/index.md
  - Manuals: manuals/index.md
  - Brand Guidelines: brand-guidelines/index.md