site_name: HoverStop Documentation
site_url: https://hover-stop.github.io/docs
repo_url: https://github.com/hover-stop/docs
nav:
  - Home: index.md
  - Technical Data: content/technical-data/index.md
  - Build Guides: content/build-guides/index.md
  - Manuals: content/manuals/index.md
  - Brand Guidelines: content/brand-guidelines/index.md
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - meta
  - attr_list
theme:
  name: material
  palette:
    primary: "blue"
    accent: "orange"
  custom_dir: overrides
extra_css:
  - assets/css/custom.css
extra_javascript:
  - assets/js/custom.js