name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Build site
      run: |
        mkdocs build --verbose

    - name: Ensure assets directory in docs
      run: |
        mkdir -p site/assets/css
        mkdir -p site/assets/fonts
        mkdir -p site/assets/img
        cp -r assets/css/* site/assets/css/
        cp -r assets/fonts/* site/assets/fonts/
        cp -r assets/img/* site/assets/img/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true